title = 'Platform Docs'

[menus]
    [[menus.secondary]]
        name = "Menu 1 ğŸ‘ˆğŸ¾"
        weight = 1
        url = ""
     [[menus.secondary]]
        name = "Menu 2 ğŸ‘‹ğŸ¿"
        weight = 2
        url = ""
    [[menus.secondary]]
        name = "Menu 3 ğŸ«¶ğŸ¼"
        weight = 3
        url = ""


[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum-labs/common-theme" 
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum-labs/common-content" 
    [[module.imports.mounts]]
      source = "en"
      target = "content"


theme = "common-theme"